language:python
-"2.7"
language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.2
before_install:
  - sudo apt-get -qq update
  
install: "pip install -r requirements.txt"
# command to run tests
script: python -m unittest discover
